# Generated by Django 4.0 on 2021-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
